apiVersion: v1
kind: Service
metadata:
  name: med-assert-api
  namespace: med-assert
  labels:
    app.kubernetes.io/name: med-assert
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: med-assert
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
